apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-24T08:54:58Z"
  generateName: cockroachdb-
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/name: cockroachdb
    controller-revision-hash: cockroachdb-55859bd459
    crdb: is-cool
    statefulset.kubernetes.io/pod-name: cockroachdb-1
  name: cockroachdb-1
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: cockroachdb
    uid: 11ec4149-84fd-40b4-bd32-bb23d93a7173
  resourceVersion: "404328"
  uid: f95ec80b-0149-4c8b-ab0c-02d8ad00d161
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /bin/bash
    - -ecx
    - 'exec /cockroach/cockroach.sh start --advertise-host=$(POD_NAME).cockroachdb.default
      --certs-dir=/cockroach/cockroach-certs/ --http-port=8080 --sql-addr=:26257 --listen-addr=:26258
      --log="{sinks: {stderr: {channels: [OPS, HEALTH], redact: true}}}" --cache $(expr
      $MEMORY_LIMIT_MIB / 4)MiB --max-sql-memory $(expr $MEMORY_LIMIT_MIB / 4)MiB
      --join=cockroachdb-0.cockroachdb.default:26258,cockroachdb-1.cockroachdb.default:26258,cockroachdb-2.cockroachdb.default:26258'
    env:
    - name: COCKROACH_CHANNEL
      value: kubernetes-operator-unknown
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.cpu
    - name: MEMORY_LIMIT_MIB
      valueFrom:
        resourceFieldRef:
          divisor: 1Mi
          resource: limits.memory
    image: cockroachdb/cockroach:v22.2.5
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - sh
          - -c
          - /cockroach/cockroach node drain --certs-dir=/cockroach/cockroach-certs/
            || exit 0
    name: db
    ports:
    - containerPort: 26258
      name: grpc
      protocol: TCP
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 26257
      name: sql
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /health?ready=1
        port: http
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cockroach/cockroach-data/
      name: datadir
    - mountPath: /cockroach/cockroach-certs/
      name: emptydir
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: cockroachdb-1
  initContainers:
  - command:
    - /bin/sh
    - -c
    - '>- cp -p /cockroach/cockroach-certs-prestage/..data/* /cockroach/cockroach-certs/
      && chmod 600 /cockroach/cockroach-certs/*.key && chown 1000581000:1000581000
      /cockroach/cockroach-certs/*.key'
    image: cockroachdb/cockroach:v22.2.5
    imagePullPolicy: IfNotPresent
    name: db-init
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cockroach/cockroach-certs-prestage/
      name: certs
    - mountPath: /cockroach/cockroach-certs/
      name: emptydir
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000581000
    runAsUser: 1000581000
  serviceAccount: cockroachdb-sa
  serviceAccountName: cockroachdb-sa
  subdomain: cockroachdb
  terminationGracePeriodSeconds: 300
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: datadir-cockroachdb-1
  - emptyDir: {}
    name: emptydir
  - name: certs
    projected:
      defaultMode: 400
      sources:
      - secret:
          items:
          - key: ca.crt
            mode: 504
            path: ca.crt
          - key: tls.crt
            mode: 504
            path: node.crt
          - key: tls.key
            mode: 400
            path: node.key
          name: cockroachdb-node
      - secret:
          items:
          - key: tls.crt
            mode: 504
            path: client.root.crt
          - key: tls.key
            mode: 400
            path: client.root.key
          name: cockroachdb-root
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-24T08:55:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-02-24T08:55:14Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-02-24T08:55:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-02-24T08:54:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b68a688f83f19020f27578c62dc8ce509c654cd59acd2a01d8e2d3f440336f3e
    image: cockroachdb/cockroach:v22.2.5
    imageID: docker-pullable://cockroachdb/cockroach@sha256:110459a28fcfd0ea08ab4162dbd587302d3a00d6ef0fe3edbb0c9592ff8d0a3b
    lastState: {}
    name: db
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-02-24T08:55:00Z"
  hostIP: 192.168.49.2
  initContainerStatuses:
  - containerID: docker://d0586394d08035bb38e8e4b95b92b4efb022dbce383fec14b677cd2dd0e54eb9
    image: cockroachdb/cockroach:v22.2.5
    imageID: docker-pullable://cockroachdb/cockroach@sha256:110459a28fcfd0ea08ab4162dbd587302d3a00d6ef0fe3edbb0c9592ff8d0a3b
    lastState: {}
    name: db-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://d0586394d08035bb38e8e4b95b92b4efb022dbce383fec14b677cd2dd0e54eb9
        exitCode: 0
        finishedAt: "2023-02-24T08:54:59Z"
        reason: Completed
        startedAt: "2023-02-24T08:54:59Z"
  phase: Running
  podIP: 172.17.0.6
  podIPs:
  - ip: 172.17.0.6
  qosClass: Burstable
  startTime: "2023-02-24T08:54:58Z"
