CREATE USER IF NOT EXISTS '_MONITOR_'@'%' IDENTIFIED BY '_MONITOR_' WITH MAX_USER_CONNECTIONS 30;
GRANT ALL PRIVILEGES ON *.* TO '_MONITOR_'@'%' IDENTIFIED BY '_MONITOR_' WITH GRANT OPTION;
FLUSH PRIVILEGES;
delete from mysql.user where user = '' and password = '';