[local]
path=data
ip=${OVERRIDE}
port=${OVERRIDE}
#core_number
#event_dispatcher_num
#node_memory_limit_mb
checkpoint_interval=60
enable_data_store=none
enable_wal=none
[cluster]
# ip_port_list
# txlog_service_list
# txlog_group_replica_num
[store]
#cass_hosts
#cass_keyspace=eloqkv
[metrics]
enable_metrics=${OVERRIDE}
