[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test", "--tests"]
dependencies = ["clippy"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.pkg]
script = '''
#!/bin/bash
echo "build package"
MONO_DIST_DIR="mono_waiter_dist"
function build_package() {
  mkdir_dist_dir=`rm -rf "$MONO_DIST_DIR" && mkdir -p "$MONO_DIST_DIR" && mkdir -p "$MONO_DIST_DIR"/config`
  cp -r ./config/* "$MONO_DIST_DIR/config"
  cp ./target/release/monograph_waiter "$MONO_DIST_DIR"
}
build_package
'''

[tasks.all-flow]
dependencies = [
    "clean",
    "format",
    "build",
    "pkg"
]