FROM ubuntu:24.04

RUN set -eux; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt update; \
    apt install -y --no-install-recommends sudo wget curl ca-certificates openssh-server iproute2 redis-tools git rsync python3; \
    rm -rf /var/lib/apt/lists/*

RUN useradd -rm -s /bin/bash -g sudo eloquser && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    mkdir -p /home/eloquser/.ssh && \
    chown -R eloquser:sudo /home/eloquser/.ssh && \
    chmod 700 /home/eloquser/.ssh

# Key is mounted at runtime as /tmp/ssh_key.pub
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 22 6379 16379
ENTRYPOINT ["/entrypoint.sh"]
