{
 "title": "tx_service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": {
     "query": "label_values({node_id=~\".+\"}, node_id)"
    }
   },
   {
    "name": "core_id",
    "label": "core_id",
    "query": {
     "query": "label_values({core_id=~\".+\"}, core_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(tx_post_process_total{node_id=~\"$node_id\", core_id=~\"$core_id\"}[$__rate_interval])",
     "legendFormat": "node: {{node_id}}  core_id: {{core_id}}"
    }
   ]
  },
  {
   "title": "CC Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "cc_queue_length{node_id=~\"$node_id\", core_id=~\"$core_id\"}",
     "legendFormat": "node: {{node_id}}  core: {{core_id}} "
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Run One Round Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(run_one_round_duration_bucket{core_id=~\"$core_id\", node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p99, node: {{node_id}}  core: {{core_id}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(run_one_round_duration_bucket{core_id=~\"$core_id\", node_id=\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p90, node: {{node_id}}  core: {{core_id}}"
    }
   ]
  },
  {
   "title": "Tx Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(tx_execution_duration_bucket{core_id=~\"$core_id\", node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p99, node: {{node_id}}  core: {{core_id}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(tx_execution_duration_bucket{core_id=~\"$core_id\", node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p90, node: {{node_id}}  core: {{core_id}}"
    }
   ]
  },
  {
   "title": "Tx Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(tx_latency_bucket{core_id=~\"$core_id\", node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p99, node: {{node_id}}  core: {{core_id}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(tx_latency_bucket{core_id=~\"$core_id\", node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p90, node: {{node_id}}  core: {{core_id}}"
    }
   ]
  },
  {
   "title": "Process CC Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(process_cc_request_duration_bucket{core_id=~\"$core_id\", node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p99, node: {{node_id}}  core: {{core_id}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(process_cc_request_duration_bucket{core_id=~\"$core_id\", node_id=\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "p90, node: {{node_id}}  core: {{core_id}}"
    }
   ]
  }
 ]
}