{
 "title": "overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": {
     "query": "label_values({node_id=~\".+\"}, node_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(tx_post_process_total{node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "TPS (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(tx_post_process_total{node_id=~\"$node_id\"}[$__rate_interval])) by (node_id)",
     "legendFormat": "node: {{node_id}} "
    }
   ]
  },
  { "title": "TX Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TX Latency (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tx_latency_bucket{node_id=~\"$node_id\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "TX Latency (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tx_latency_bucket{node_id=~\"$node_id\"}[$__rate_interval])) by (le, node_id))",
     "legendFormat": "p99, node: {{node_id}} "
    }
   ]
  },
  {
   "title": "Run One Round",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Tx Execution Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tx_execution_duration_bucket[$__rate_interval])) by (le, node_id))",
       "legendFormat": "p99, node: {{node_id}}"
      }
     ]
    },
    {
     "title": "Process CC Requests Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(process_cc_request_duration_bucket{node_id=~\"$node_id\"}[$__rate_interval])) by (le, node_id))",
       "legendFormat": "p99, node: {{node_id}} "
      }
     ]
    },
    {
     "title": "Run One Round Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(run_one_round_duration_bucket{node_id=~\"$node_id\"}[$__rate_interval])) by (le, node_id))",
       "legendFormat": "p99, node: {{node_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "CC Shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CC Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg(cc_queue_length{node_id=~\"$node_id\"}) by (node_id)",
       "legendFormat": "node: {{node_id}} "
      }
     ]
    }
   ]
  }
 ]
}