resources:
  - name: monograph_waiter
    icon: github
    source:
      branch: main
      private_key: ((git-key))
      uri: git@github.com:monographdb/monograph_waiter.git
    type: git
  - name: image_ubuntu2004
    source:
      repository: monographdb/waiter-build-ubuntu20
    type: registry-image

jobs:
  - name: waiter-build
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: monograph_waiter
            - get: image_ubuntu2004
      - task: build_waiter
        image: image_ubuntu2004
        file: monograph_waiter/concourse/one-click.yaml
