resources:
  - name: monograph_waiter
    icon: github
    source:
      branch: one-click
      private_key: ((git-key))
      uri: git@github.com:monographdb/monograph_waiter.git
    type: git
  - name: base_image
    source:
      username: monographdb
      password: Mono_cz158#
      repository: monographdb/monograph-dev-ci-ubuntu2004
    type: registry-image

jobs:
  - name: waiter-build
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: monograph_waiter
            - get: base_image
      - task: waiter-build
        image: base_image
        params:
          PIPELINE: "waiter-build"
        file: monograph_waiter/concourse/one-click.yaml
