{
 "title": "EloqSQL Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   {
    "name": "full_cluster_name",
    "label": "Full Cluster Name",
    "query": {
     "query": "label_values(mysql_max_connections{namespace=~\"$namespace\"},eloqdata_cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(mysql_max_connections,namespace)"
    }
   },
   {
    "name": "eloqdata_cluster",
    "label": "EloqData Cluster",
    "query": {
     "query": "label_values(mysql_max_connections{namespace=~\"$namespace\"},eloqdata_cluster)"
    }
   },
   {
    "name": "eloqdata_server",
    "label": "EloqData Server",
    "query": {
     "query": "label_values(memory_limit{namespace=~\"$namespace\", eloqdata_cluster=~\"$eloqdata_cluster\"},instance)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "99.9,99, 95, 90, 50" },
   {
    "name": "dml_type",
    "label": "DML Type",
    "query": {
     "query": "label_values(mysql_dml_total, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status Up / Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up / Down",
     "type": "status-history",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "up{instance=~\"$eloqdata_server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "All Discovered Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{instance=~\"$eloqdata_server\"})by(job)",
     "legendFormat": "Current TPS"
    }
   ]
  },
  {
   "title": "Alive Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$eloqdata_server\"})",
     "legendFormat": "Current TPS"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 + sum(memory_usage{instance=~\"$eloqdata_server\"})) / (1 + sum(memory_limit{instance=~\"$eloqdata_server\"}))",
     "legendFormat": "Current TPS"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 + sum(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$eloqdata_server\"}[5s]))) / (1 + sum(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$eloqdata_server\"}[5s])) + sum(delta(cache_hit_or_miss_total{type=\"miss\",instance=~\"$eloqdata_server\"}[5s])))",
     "legendFormat": "Current TPS"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_processed_tx_total{instance=~\"$eloqdata_server\"}[5s]))",
     "legendFormat": "Current QPS"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_processed_query_total{instance=~\"$eloqdata_server\"}[5s]))",
     "legendFormat": "Current QPS"
    }
   ]
  },
  {
   "title": "TX Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum by (le)(rate(mysql_tx_duration_bucket{instance=~\"$eloqdata_server\"}[5s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Pool Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (memory_limit{instance=~\"$eloqdata_server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (mysql_max_connections{instance=~\"$eloqdata_server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (mysql_connection_count{instance=~\"$eloqdata_server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Connections",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (mysql_max_connections{instance=~\"$eloqdata_server\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (mysql_connection_count{instance=~\"$eloqdata_server\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL TX Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL TPS (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mysql_processed_tx_total{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "MySQL TPS (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(mysql_processed_tx_total{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MySQL TX Latency (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le)(rate(mysql_tx_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile"
      }
     ]
    },
    {
     "title": "MySQL TX Latency (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, instance)(rate(mysql_tx_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL DML Metrics (cluster view)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "DML Count (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type)(rate(mysql_dml_total{instance=~\"$eloqdata_server\", type=~\"$dml_type\"}[$__rate_interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "DML Latency (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, type)(rate(mysql_dml_duration_bucket{instance=~\"$eloqdata_server\", type=~\"$dml_type\"}[$__rate_interval])))",
       "legendFormat": "p$percentile , {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL DML Count (command view)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "DML Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "repeat": "dml_type",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type, instance)(rate(mysql_dml_total{instance=~\"$eloqdata_server\", type=~\"$dml_type\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL DML Latency (command view)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "DML Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "repeat": "dml_type",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, type, instance)(rate(mysql_dml_duration_bucket{instance=~\"$eloqdata_server\", type=~\"$dml_type\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{instance}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "TX Service TPS (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tx_processed_total{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "TX Service TPS (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance)(rate(tx_processed_total{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "TX Service TX Latency (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le)(rate(tx_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile "
      }
     ]
    },
    {
     "title": "TX Service TX Latency (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100 , sum by (le, instance)(rate(tx_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 + sum(memory_usage{instance=~\"$eloqdata_server\"})) / (1 + sum(memory_limit{instance=~\"$eloqdata_server\"}))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Memory Usage (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 + sum by (instance)(memory_usage{instance=~\"$eloqdata_server\"})) / (1 + sum by (instance) (memory_limit{instance=~\"$eloqdata_server\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit rate (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 + sum(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$eloqdata_server\"}[$__rate_interval]))) / (1 + sum(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$eloqdata_server\"}[$__rate_interval])) + sum(delta(cache_hit_or_miss_total{type=\"miss\",instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Cache Hit rate (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 + sum by(instance)(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$eloqdata_server\"}[$__rate_interval]))) / (1 + sum by(instance)(delta(cache_hit_or_miss_total{type=\"hits\",instance=~\"$eloqdata_server\"}[$__rate_interval])) + sum by(instance)(delta(cache_hit_or_miss_total{type=\"miss\", instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Busy Round",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Busy Round Active TXs Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (instance) (rate(busy_round_active_tx_count{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Busy Round Processed CC Requests Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (instance) (rate(busy_round_processed_cc_request_count{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Busy Round Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, instance)(rate(busy_round_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{instance}}"
      }
     ]
    },
    {
     "title": "Empty Round Ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (instance) (avg_over_time (empty_round_ratio{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read KV Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read KV Requests Count (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(kv_read_total{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Read KV Requests Count (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(kv_read_total{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read KV Latency (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le) (rate(kv_read_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, total"
      }
     ]
    },
    {
     "title": "Read KV Latency (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, instance) (rate(kv_read_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Slice from KV Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Slice form KV Count (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(kv_load_slice_total{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Load Slice from KV Count (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(kv_load_slice_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Load Slice form KV Latency (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le) (rate(kv_load_slice_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, total"
      }
     ]
    },
    {
     "title": "Load Slice from KV Latency (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, instance) (rate(kv_load_slice_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flush Records to KV Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flush Records to Base Table (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(kv_flush_rows_total{type=\"base\", instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "total {{table_type}}"
      }
     ]
    },
    {
     "title": "Flush Records to Base Table (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(kv_flush_rows_total{type=\"base\", instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{table_type}}"
      }
     ]
    },
    {
     "title": "Flush Records to Archive Table (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(kv_flush_rows_total{type=\"archive\", instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "total {{table_type}}"
      }
     ]
    },
    {
     "title": "Flush Records to Archive Table (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(kv_flush_rows_total{type=\"archive\", instance=~\"$eloqdata_server\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{table_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote Request Metrics (overview)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "In-flight Requests Count (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type)(remote_request_in_flight_count{instance=~\"$eloqdata_server\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "In-flight Requests Latency (overview)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, type) (rate(remote_request_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote Requests Metrics (instance view)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "In-flight Requests Count (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "repeat": "eloqdata_server",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type, instance)(remote_request_in_flight_count{instance=~\"$eloqdata_server\"})",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    },
    {
     "title": "Remote Requests Latency (instance view)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "repeat": "eloqdata_server",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile / 100, sum by (le, type, instance) (rate(remote_request_duration_bucket{instance=~\"$eloqdata_server\"}[$__rate_interval])))",
       "legendFormat": "p$percentile, {{instance}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mysqld Log",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{job=\"mysqld-log\"}"
      }
     ]
    }
   ]
  }
 ]
}